service: client
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "0s"

instance_class: F1
automatic_scaling:
  max_idle_instances: 1

handlers:
  - url: /static/
    static_dir: dist/static
    secure: always

  - url: /(robots\.txt|manifest\.json)$
    static_files: dist/\1
    upload: dist/(robots\.txt|manifest\.json)$
    secure: always

  - url: /(.*\.js)$
    static_files: dist/\1
    upload: dist/.*\.js$
    secure: always
    http_headers:
      Content-Type: application/javascript
      Cache-Control: max-age=0

  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)
    secure: always

  - url: /
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
