#!/usr/bin/env bash
python=/home/milan/venv/ands/bin/python
appengine=/home/milan/google_appengine
storage=/home/milan/work/andsnews_storage/
DATE=`date +%Y%m%d`

case $1 in
  devel)
    $python $appengine/dev_appserver.py --storage_path=$storage local.yaml
    exit ;;
  build)
    cd client
    echo $(pwd)
    sed -i -E "/version/s/[[:digit:]]{8}/$DATE/g" "src/app-shell.html"
    polymer build
    cd ..
    exit ;;
  deploy)
    gcloud app deploy -v $DATE app.yaml index.yaml dos.yaml queue.yaml
    exit ;;
  *)
    echo $"Usage: $0 devel  - Run development server"
    echo $"       $0 build  - Run polymer build"
    echo $"       $0 deploy - Deploy app version $DATE"
    exit 1
esac
