application: andsnews
version: 1607
runtime: python27
api_version: 1
threadsafe: true
default_expiration: 7d

libraries:
- name: PIL
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: webapp2
  version: latest
- name: webob
  version: latest
- name: numpy
  version: latest

handlers:
- url: /
  static_files: app/index.html
  upload: app/index.html
  secure: always

- url: /robots.txt
  static_files: app/robots.txt
  upload: app/robots.txt
  secure: always

- url: /favicon.ico
  static_files: app/favicon.ico
  upload: app/favicon.ico
  secure: always

- url: /bower_components/
  static_dir: app/bower_components
  secure: always

- url: /node_modules/
  static_dir: app/node_modules
  secure: always

- url: /elements/
  static_dir: app/elements
  secure: always

- url: /images/
  static_dir: app/images
  secure: always

- url: /scripts/
  static_dir: app/scripts
  secure: always

- url: /styles/
  static_dir: app/styles
  secure: always

- url: /static/(.*\.(less|scss))$
  static_files: static/\1
  upload: static/.*\.(less|scss)$
  mime_type: text/css

- url: /static/(.*\.map)$
  static_files: static/\1
  upload: static/.*\.map$
  mime_type: application/json

- url: /static/font/(.*\.ttf)$
  static_files: static/font/\1
  upload: static/font/.*\.ttf$
  mime_type: font/ttf
  expiration: 1000d

- url: /static/font/(.*\.woff2)$
  static_files: static/font/\1
  upload: static/font/.*\.woff2$
  mime_type: application/font-woff2
  expiration: 1000d

- url: /static/font/(.*\.eot)$
  static_files: static/font/\1
  upload: static/font/.*\.eot$
  mime_type: application/vnd.ms-fontobject
  expiration: 1000d

- url: /static
  static_dir: static

- url: /mapreduce(/.*)?
  login: admin
  script: mapreduce.main.APP

- url: /tests/.*
  login: admin
  script: aeta.main.APP

#- url: /stats.*
#  script: google.appengine.ext.appstats.ui.app

- url: /.*
  script: main.app
  secure: always

inbound_services:
- warmup

builtins:
- deferred: on
#- appstats: on
#- remote_api: on

#skip_files:
#- ^(.*/)?.*\.py[co]$
#- ^(.*/)?\..*$
