runtime: python27
api_version: 1
threadsafe: true
default_expiration: "0s"

libraries:
- name: PIL
  version: latest
- name: webapp2
  version: latest
- name: webob
  version: latest
- name: numpy
  version: latest

handlers:
- url: /api/.*
  script: main.app
  secure: always

- url: /sitemap\.xml
  script: main.app
  secure: always

- url: /_ah/warmup
  script: main.app
  secure: always

- url: /(robots\.txt|manifest\.json)$
  static_files: p2/build/default/\1
  upload: p2/build/default/(robots\.txt|manifest\.json)$
  secure: always

- url: /(service-worker\.js|firebase-messaging-sw\.js)$
  static_files: p2/build/default/\1
  upload: p2/build/default/(service-worker\.js|firebase-messaging-sw\.js)$
  secure: always

- url: /src/
  static_dir: p2/build/default/src
  secure: always

- url: /images/
  static_dir: p2/build/default/images
  secure: always

- url: /bower_components/
  static_dir: p2/build/default/bower_components
  secure: always

- url: /index\.html
  static_files: p2/build/default/index.html
  upload: p2/build/default/index.html
  secure: always

- url: /.*
  static_files: p2/build/default/index.html
  upload: p2/build/default/index.html
  secure: always

inbound_services:
- warmup

builtins:
- deferred: on
#- appstats: on
#- remote_api: on

skip_files:
- ^(.*/)?.*~$
- ^(.*/)?\..*$
- ^(.*/)?.*\.py[co]$
- lib/PIL*
- ^docs
- ^p2/(src|test|images)
- ^p2/bower_components
- ^client
