application: andsnews
version: 1612
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "0s"

libraries:
- name: PIL
  version: latest
- name: webapp2
  version: latest
- name: webob
  version: latest
- name: numpy
  version: latest

# client -> client/build/unbundled

handlers:
- url: /
  static_files: client/index.html
  upload: client/index.html
  secure: always

- url: /favicon.ico
  static_files: client/favicon.ico
  upload: client/favicon.ico
  secure: always

- url: /robots\.txt
  static_files: client/robots.txt
  upload: client/robots.txt
  secure: always

- url: /service-worker\.js
  static_files: client/service-worker.js
  upload: client/service-worker.js
  secure: always

- url: /firebase-messaging-sw\.js
  static_files: client/firebase-messaging-sw.js
  upload: client/firebase-messaging-sw.js
  secure: always

- url: /manifest\.json
  static_files: client/manifest.json
  upload: client/manifest.json
  secure: always

- url: /src/
  static_dir: client/src
  secure: always

- url: /images/
  static_dir: client/images
  secure: always

- url: /bower_components/
  static_dir: client/bower_components
  secure: always

- url: /api/.*
  script: main.app
  secure: always

- url: /sitemap\.xml
  script: main.app
  secure: always

- url: /tests/.*
  login: admin
  script: aeta.main.APP

inbound_services:
- warmup

builtins:
- deferred: on
#- appstats: on
#- remote_api: on

skip_files:
- ^(.*/)?.*~$
- ^(.*/)?\..*$
- ^(.*/)?.*\.py[co]$
- ^docs
- ^client/build/bundled
- ^client/(src|test|images)
- ^client/bower_components
