runtime: python38
default_expiration: '0s'

instance_class: F2
automatic_scaling:
  max_instances: 2
  max_idle_instances: 1

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'credentials.json'

handlers:
  - url: /robots\.txt$
    static_files: vue3/dist/\1
    upload: vue3/dist/robots\.txt$
    secure: always

  - url: /manifest\.webmanifest$
    static_files: vue3/dist/\1
    upload: vue3/dist/manifest\.webmanifest$
    http_headers:
      Content-Type: application/manifest+json
      Cache-Control: max-age=0
    secure: always

  - url: /(.*\.js)$
    static_files: vue3/dist/\1
    upload: vue3/dist/.*\.js$
    http_headers:
      Content-Type: application/javascript
      Cache-Control: max-age=0
    secure: always

  - url: /index.html
    static_files: vue3/dist/index.html
    upload: vue3/dist/index.html
    secure: always

  - url: /assets
    static_dir: vue3/dist/assets
    secure: always

  - url: /icons
    static_dir: vue3/dist/icons
    secure: always

  - url: /api/.*
    script: auto
    secure: always

  - url: /.*
    static_files: vue3/dist/index.html
    upload: vue3/dist/index.html
    secure: always

inbound_services:
  - warmup
