runtime: python310
default_expiration: "0s"

instance_class: F2
automatic_scaling:
  max_instances: 2
  max_idle_instances: 1

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials.json"

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /
    static_files: vue3/dist/pwa/index.html
    upload: vue3/dist/pwa/index.html
    secure: always

  - url: /sw.js
    static_files: vue3/dist/pwa/sw.js
    upload: vue3/dist/pwa/sw.js
    secure: always
    http_headers:
      Cache-Control: no-cache

  - url: /(.*)
    static_files: vue3/dist/pwa/\1
    upload: vue3/dist/pwa/(.*)
    secure: always

inbound_services:
  - warmup
