application: andsnews
version: 1411
runtime: python27
api_version: 1
threadsafe: true
default_expiration: 7d

libraries:
- name: PIL
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: webapp2
  version: latest
- name: webob
  version: latest
- name: numpy
  version: latest

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots.txt

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/x-icon

- url: /static/css/(.*)\.less
  static_files: static/css/\1.less
  upload: static/css/.*.less
  mime_type: text/css

- url: /static/(.*)\.map
  static_files: static/\1.map
  upload: static/.*.map
  mime_type: application/json

- url: /static
  static_dir: static

- url: /mapreduce(/.*)?
  login: admin
  script: mapreduce.main.APP

- url: /tests/.*
  login: admin
  script: aeta.main.APP

#- url: /stats.*
#  script: google.appengine.ext.appstats.ui.app

- url: /.*
  script: main.app
  secure: always

inbound_services:
- warmup
- xmpp_message

builtins:
- deferred: on
#- appstats: on
#- remote_api: on

error_handlers:
- file: templates/errors/error.html
- error_code: dos_api_denial
  file: templates/errors/dos_api_denial.html
- error_code: over_quota
  file: templates/errors/over_quota.html
- error_code: timeout
  file: templates/errors/timeout.html

skip_files:
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$