service: default
runtime: python37
default_expiration: "0s"

instance_class: F2
automatic_scaling:
  max_instances: 2
  min_instances: 0

handlers:
  - url: /(robots\.txt|manifest\.json)$
    static_files: dist/\1
    upload: dist/(robots\.txt|manifest\.json)$
    secure: always

  - url: /(.*\.js)$
    static_files: vue2/dist/\1
    upload: vue2/dist/.*\.js$
    secure: always
    http_headers:
      Content-Type: application/javascript
      Cache-Control: max-age=0

  - url: /index.html
    static_files: vue2/dist/index.html
    upload: vue2/dist/index.html
    secure: always

  - url: /static
    static_dir: vue2/dist/static
    secure: always

  - url: /api/.*
    script: auto
    secure: always

  - url: /.*
    static_files: vue2/dist/index.html
    upload: vue2/dist/index.html
    secure: always

inbound_services:
  - warmup
