application: andsnews
version: 16082323
runtime: python27
api_version: 1
threadsafe: true
default_expiration: 1d

libraries:
- name: PIL
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: webapp2
  version: latest
- name: webob
  version: latest
- name: numpy
  version: latest

# client -> client/build/bundled

handlers:
- url: /bower_components/
  static_dir: client/bower_components
  secure: always

- url: /src/
  static_dir: client/src
  secure: always

- url: /images/
  static_dir: client/images
  secure: always

- url: /service-worker.js
  static_files: client/service-worker.js
  upload: client/service-worker.js
  secure: always

- url: /manifest.json
  static_files: client/manifest.json
  upload: client/manifest.json
  secure: always

- url: /index.html
  static_files: client/index.html
  upload: client/index.html
  secure: always

- url: /robots.txt
  static_files: client/robots.txt
  upload: client/robots.txt
  secure: always

- url: /
  static_files: client/index.html
  upload: client/index.html
  secure: always

- url: /api/.*
  script: main.app
  secure: always

####################################################

#- url: /favicon.ico
#  static_files: app/favicon.ico
#  upload: app/favicon.ico
#  secure: always

- url: /static
  static_dir: static

- url: /mapreduce(/.*)?
  login: admin
  script: mapreduce.main.APP

- url: /tests/.*
  login: admin
  script: aeta.main.APP

- url: /admin/.*
  script: main.app
  secure: always

inbound_services:
- warmup

builtins:
- deferred: on
#- appstats: on
#- remote_api: on

#skip_files:
#- ^(.*/)?.*\.py[co]$
#- ^(.*/)?\..*$
