runtime: python38
default_expiration: '0s'

instance_class: F2
automatic_scaling:
  max_instances: 2
  max_idle_instances: 1

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'credentials.json'

handlers:
  - url: /(robots\.txt|manifest\.json)$
    static_files: vue3/dist/\1
    upload: vue3/dist/(robots\.txt|manifest\.json)$
    secure: always

  - url: /(.*\.js)$
    static_files: vue3/dist/\1
    upload: vue3/dist/.*\.js$
    secure: always
    http_headers:
      Content-Type: application/javascript
      Cache-Control: max-age=0

  - url: /index.html
    static_files: vue3/dist/index.html
    upload: vue3/dist/index.html
    secure: always

  - url: /assets
    static_dir: vue3/dist/assets
    secure: always

  - url: /api/.*
    script: auto
    secure: always

  - url: /.*
    static_files: vue3/dist/index.html
    upload: vue3/dist/index.html
    secure: always

inbound_services:
  - warmup
