application: andsnews
service: api
version: v1
runtime: python27
api_version: 1
threadsafe: true

instance_class: B1
manual_scaling:
  instances: 1

libraries:
- name: PIL
  version: latest
- name: webapp2
  version: latest
- name: webob
  version: latest
- name: numpy
  version: latest

handlers:
- url: /sitemap\.xml
  script: main.app
  secure: always

- url: /api/.*
  script: main.app
  secure: always

- url: /tests/.*
  login: admin
  script: aeta.main.APP

builtins:
- deferred: on
#- appstats: on
#- remote_api: on

skip_files:
- ^(.*/)?.*~$
- ^(.*/)?\..*$
- ^(.*/)?.*\.py[co]$
- ^docs
