// auth
export const SAVE_USER = 'SAVE_USER'
export const SET_TOKEN = 'SET_TOKEN'
// app
export const ADD_UPLOADED = 'ADD_UPLOADED'
export const DELETE_UPLOADED = 'DELETE_UPLOADED'
export const ADD_FAILED = 'ADD_FAILED'
export const RESET_FAILED = 'RESET_FAILED'
export const CHANGE_UPLOAD_STATUS = 'CHANGE_UPLOAD_STATUS'
export const SET_UPLOAD_PERCENTAGE = 'SET_UPLOAD_PERCENTAGE'

export const ADD_RECORD = 'ADD_RECORD'
export const UPDATE_RECORD = 'UPDATE_RECORD'
export const DELETE_RECORD = 'DELETE_RECORD'

export const SAVE_FIND_FORM = 'SAVE_FIND_FORM'
export const UPDATE_OBJECTS = 'UPDATE_OBJECTS'
export const SET_CLEAR = 'SET_CLEAR'
export const RESET_OBJECTS = 'RESET_OBJECTS'
export const RESET_PAGINATOR = 'RESET_PAGINATOR'

export const SET_BUCKET = 'SET_BUCKET'
export const SET_COUNTERS = 'SET_COUNTERS'
export const SET_LAST_BY_YEAR = 'SET_LAST_BY_YEAR'
export const UPDATE_VALUES = 'UPDATE_VALUES'
export const UPDATE_VALUES_EMAIL = 'UPDATE_VALUES_EMAIL'
export const UPDATE_LAST_BY_YEAR = 'UPDATE_LAST_BY_YEAR'

export const SET_BUSY = 'SET_BUSY'
export const SET_ERROR = 'SET_ERROR'
export const SET_SNACKBAR = 'SET_SNACKBAR'
export const TOGGLE_THEME = 'TOGGLE_THEME'
