service: default
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "0s"

instance_class: F1
automatic_scaling:
  max_idle_instances: 1

handlers:
- url: /(robots\.txt|manifest\.json)$
  static_files: build/default/\1
  upload: build/default/(robots\.txt|manifest\.json)$
  secure: always

- url: /bower_components/
  static_dir: build/default/bower_components
  secure: always

- url: /src/
  static_dir: build/default/src
  secure: always

- url: /images/
  static_dir: build/default/images
  secure: always

- url: /(service-worker\.js|firebase-messaging-sw\.js)$
  static_files: build/default/\1
  upload: build/default/(service-worker\.js|firebase-messaging-sw\.js)$
  secure: always

- url: /.*
  static_files: build/default/index.html
  upload: build/default/index.html
  secure: always

skip_files:
- ^bower_components
- ^node_modules
- ^(src|test|images)
