#!/usr/bin/env bash

sizes=(32 48 72 96 144 192 512)

for i in ${sizes[@]}; do
  if [ $i = "32" ]; then
    file=logo.png
  else
    file=manifest/icon-$i\x$i.png
  fi
  inkscape -z -e $file -w $i -h $i logo.svg
  echo $file
done
exit 0
