#!/usr/bin/env bash

sizes=(48 72 96 144 192 512)

for i in ${sizes[@]}; do
  file=manifest/icon-$i\x$i.png
  inkscape -z -e $file -w $i -h $i logo.svg
  echo $file
done

file=logo.png
inkscape -z -e $file -w 192 -h 192 logo.svg
echo $file
exit 0
