service: default
runtime: python37
default_expiration: "0s"

instance_class: F2
automatic_scaling:
  max_instances: 2

handlers:
  - url: /.*
    script: auto
    secure: always

inbound_services:
  - warmup
